//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Cliente : XPLiteObject
    {
        int fIdClient;
        [Key(true)]
        public int IdClient
        {
            get { return fIdClient; }
            set { SetPropertyValue<int>(nameof(IdClient), ref fIdClient, value); }
        }
        string fNombreClient;
        [Size(60)]
        public string NombreClient
        {
            get { return fNombreClient; }
            set { SetPropertyValue<string>(nameof(NombreClient), ref fNombreClient, value); }
        }
        string fApellidoClient;
        [Size(60)]
        public string ApellidoClient
        {
            get { return fApellidoClient; }
            set { SetPropertyValue<string>(nameof(ApellidoClient), ref fApellidoClient, value); }
        }
        string fSexoClient;
        [Size(9)]
        public string SexoClient
        {
            get { return fSexoClient; }
            set { SetPropertyValue<string>(nameof(SexoClient), ref fSexoClient, value); }
        }
        string fDocumentoCLient;
        [Size(20)]
        public string DocumentoCLient
        {
            get { return fDocumentoCLient; }
            set { SetPropertyValue<string>(nameof(DocumentoCLient), ref fDocumentoCLient, value); }
        }
        string fCelularClient;
        [Size(9)]
        public string CelularClient
        {
            get { return fCelularClient; }
            set { SetPropertyValue<string>(nameof(CelularClient), ref fCelularClient, value); }
        }
        string fCorreoClient;
        [Size(80)]
        public string CorreoClient
        {
            get { return fCorreoClient; }
            set { SetPropertyValue<string>(nameof(CorreoClient), ref fCorreoClient, value); }
        }
        string fEstado;
        [Size(10)]
        public string Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<string>(nameof(Estado), ref fEstado, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"VentaReferencesCliente")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
