//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Compra : XPLiteObject
    {
        int fIdCompra;
        [Key(true)]
        public int IdCompra
        {
            get { return fIdCompra; }
            set { SetPropertyValue<int>(nameof(IdCompra), ref fIdCompra, value); }
        }
        Proveedor fIdProv;
        [Association(@"CompraReferencesProveedor")]
        public Proveedor IdProv
        {
            get { return fIdProv; }
            set { SetPropertyValue<Proveedor>(nameof(IdProv), ref fIdProv, value); }
        }
        Empleado fIdEmpleado;
        [Association(@"CompraReferencesEmpleado")]
        public Empleado IdEmpleado
        {
            get { return fIdEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(IdEmpleado), ref fIdEmpleado, value); }
        }
        string fTipoDocumento;
        [Size(20)]
        public string TipoDocumento
        {
            get { return fTipoDocumento; }
            set { SetPropertyValue<string>(nameof(TipoDocumento), ref fTipoDocumento, value); }
        }
        string fDocumento;
        [Size(15)]
        public string Documento
        {
            get { return fDocumento; }
            set { SetPropertyValue<string>(nameof(Documento), ref fDocumento, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"DetalleCompraReferencesCompra")]
        public XPCollection<DetalleCompra> DetalleCompras { get { return GetCollection<DetalleCompra>(nameof(DetalleCompras)); } }
    }

}
