//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class DetalleVenta : XPLiteObject
    {
        int fIdDetalleVenta;
        [Key(true)]
        public int IdDetalleVenta
        {
            get { return fIdDetalleVenta; }
            set { SetPropertyValue<int>(nameof(IdDetalleVenta), ref fIdDetalleVenta, value); }
        }
        Venta fIdVenta;
        [Association(@"DetalleVentaReferencesVenta")]
        public Venta IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<Venta>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Producto fIdProd;
        [Association(@"DetalleVentaReferencesProducto")]
        public Producto IdProd
        {
            get { return fIdProd; }
            set { SetPropertyValue<Producto>(nameof(IdProd), ref fIdProd, value); }
        }
        decimal fPrecioVenta;
        [ColumnDbDefaultValue("((0))")]
        public decimal PrecioVenta
        {
            get { return fPrecioVenta; }
            set { SetPropertyValue<decimal>(nameof(PrecioVenta), ref fPrecioVenta, value); }
        }
        decimal fSubTotal;
        [ColumnDbDefaultValue("((0))")]
        public decimal SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<decimal>(nameof(SubTotal), ref fSubTotal, value); }
        }
        int fStock;
        public int Stock
        {
            get { return fStock; }
            set { SetPropertyValue<int>(nameof(Stock), ref fStock, value); }
        }
    }

}
