//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Empleado : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(60)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fApellido;
        [Size(60)]
        public string Apellido
        {
            get { return fApellido; }
            set { SetPropertyValue<string>(nameof(Apellido), ref fApellido, value); }
        }
        string fSexo;
        [Size(9)]
        public string Sexo
        {
            get { return fSexo; }
            set { SetPropertyValue<string>(nameof(Sexo), ref fSexo, value); }
        }
        string fCedula;
        [Size(16)]
        public string Cedula
        {
            get { return fCedula; }
            set { SetPropertyValue<string>(nameof(Cedula), ref fCedula, value); }
        }
        string fCelular;
        [Size(9)]
        public string Celular
        {
            get { return fCelular; }
            set { SetPropertyValue<string>(nameof(Celular), ref fCelular, value); }
        }
        string fDireccion;
        [Size(200)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fCorreo;
        [Size(80)]
        public string Correo
        {
            get { return fCorreo; }
            set { SetPropertyValue<string>(nameof(Correo), ref fCorreo, value); }
        }
        string fNombreAcceso;
        [Size(60)]
        public string NombreAcceso
        {
            get { return fNombreAcceso; }
            set { SetPropertyValue<string>(nameof(NombreAcceso), ref fNombreAcceso, value); }
        }
        string fContrasena;
        [Size(SizeAttribute.Unlimited)]
        public string Contrasena
        {
            get { return fContrasena; }
            set { SetPropertyValue<string>(nameof(Contrasena), ref fContrasena, value); }
        }
        Rol fIdRol;
        [Association(@"EmpleadoReferencesRol")]
        public Rol IdRol
        {
            get { return fIdRol; }
            set { SetPropertyValue<Rol>(nameof(IdRol), ref fIdRol, value); }
        }
        bool fEstado;
        public bool Estado
        {
            get { return fEstado; }
            set { SetPropertyValue<bool>(nameof(Estado), ref fEstado, value); }
        }
        Tema fIdTema;
        [Association(@"EmpleadoReferencesTema")]
        public Tema IdTema
        {
            get { return fIdTema; }
            set { SetPropertyValue<Tema>(nameof(IdTema), ref fIdTema, value); }
        }
        byte[] fFoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Foto
        {
            get { return fFoto; }
            set { SetPropertyValue<byte[]>(nameof(Foto), ref fFoto, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"CompraReferencesEmpleado")]
        public XPCollection<Compra> Compras { get { return GetCollection<Compra>(nameof(Compras)); } }
        [Association(@"VentaReferencesEmpleado")]
        public XPCollection<Venta> Ventas { get { return GetCollection<Venta>(nameof(Ventas)); } }
    }

}
