//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Marca : XPLiteObject
    {
        int fIdMarca;
        [Key(true)]
        public int IdMarca
        {
            get { return fIdMarca; }
            set { SetPropertyValue<int>(nameof(IdMarca), ref fIdMarca, value); }
        }
        string fNombre;
        [Size(60)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        byte[] fLogotipo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logotipo
        {
            get { return fLogotipo; }
            set { SetPropertyValue<byte[]>(nameof(Logotipo), ref fLogotipo, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"ProductoReferencesMarca")]
        public XPCollection<Producto> Productoes { get { return GetCollection<Producto>(nameof(Productoes)); } }
    }

}
