//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Negocio : XPLiteObject
    {
        int fIdNegocio;
        [Key(true)]
        public int IdNegocio
        {
            get { return fIdNegocio; }
            set { SetPropertyValue<int>(nameof(IdNegocio), ref fIdNegocio, value); }
        }
        string fNombre;
        [Size(60)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fRUC;
        [Size(11)]
        public string RUC
        {
            get { return fRUC; }
            set { SetPropertyValue<string>(nameof(RUC), ref fRUC, value); }
        }
        string fDireccion;
        [Size(200)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        byte[] fLogo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>(nameof(Logo), ref fLogo, value); }
        }
    }

}
