//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Proveedor : XPLiteObject
    {
        int fIdProv;
        [Key(true)]
        public int IdProv
        {
            get { return fIdProv; }
            set { SetPropertyValue<int>(nameof(IdProv), ref fIdProv, value); }
        }
        string fNombreProv;
        [Size(60)]
        public string NombreProv
        {
            get { return fNombreProv; }
            set { SetPropertyValue<string>(nameof(NombreProv), ref fNombreProv, value); }
        }
        string fDireccion;
        [Size(200)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        string fDocumentoProv;
        [Size(12)]
        public string DocumentoProv
        {
            get { return fDocumentoProv; }
            set { SetPropertyValue<string>(nameof(DocumentoProv), ref fDocumentoProv, value); }
        }
        string fRazonSocialProv;
        [Size(60)]
        public string RazonSocialProv
        {
            get { return fRazonSocialProv; }
            set { SetPropertyValue<string>(nameof(RazonSocialProv), ref fRazonSocialProv, value); }
        }
        string fCorreoProv;
        [Size(80)]
        public string CorreoProv
        {
            get { return fCorreoProv; }
            set { SetPropertyValue<string>(nameof(CorreoProv), ref fCorreoProv, value); }
        }
        string fTelefonoProv;
        [Size(9)]
        public string TelefonoProv
        {
            get { return fTelefonoProv; }
            set { SetPropertyValue<string>(nameof(TelefonoProv), ref fTelefonoProv, value); }
        }
        string fEstadoProv;
        [Size(10)]
        public string EstadoProv
        {
            get { return fEstadoProv; }
            set { SetPropertyValue<string>(nameof(EstadoProv), ref fEstadoProv, value); }
        }
        byte[] fLogotipo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logotipo
        {
            get { return fLogotipo; }
            set { SetPropertyValue<byte[]>(nameof(Logotipo), ref fLogotipo, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"CompraReferencesProveedor")]
        public XPCollection<Compra> Compras { get { return GetCollection<Compra>(nameof(Compras)); } }
    }

}
