//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Rol : XPLiteObject
    {
        int fIdRol;
        [Key(true)]
        public int IdRol
        {
            get { return fIdRol; }
            set { SetPropertyValue<int>(nameof(IdRol), ref fIdRol, value); }
        }
        string fNombreRol;
        [Size(60)]
        public string NombreRol
        {
            get { return fNombreRol; }
            set { SetPropertyValue<string>(nameof(NombreRol), ref fNombreRol, value); }
        }
        bool fMenuRol;
        public bool MenuRol
        {
            get { return fMenuRol; }
            set { SetPropertyValue<bool>(nameof(MenuRol), ref fMenuRol, value); }
        }
        bool fMenuEmpleado;
        public bool MenuEmpleado
        {
            get { return fMenuEmpleado; }
            set { SetPropertyValue<bool>(nameof(MenuEmpleado), ref fMenuEmpleado, value); }
        }
        bool fMenuMantenimiento;
        public bool MenuMantenimiento
        {
            get { return fMenuMantenimiento; }
            set { SetPropertyValue<bool>(nameof(MenuMantenimiento), ref fMenuMantenimiento, value); }
        }
        bool fMenuAlmacen;
        public bool MenuAlmacen
        {
            get { return fMenuAlmacen; }
            set { SetPropertyValue<bool>(nameof(MenuAlmacen), ref fMenuAlmacen, value); }
        }
        bool fMenuCompra;
        public bool MenuCompra
        {
            get { return fMenuCompra; }
            set { SetPropertyValue<bool>(nameof(MenuCompra), ref fMenuCompra, value); }
        }
        bool fMenuVenta;
        public bool MenuVenta
        {
            get { return fMenuVenta; }
            set { SetPropertyValue<bool>(nameof(MenuVenta), ref fMenuVenta, value); }
        }
        bool fMenuEstado;
        public bool MenuEstado
        {
            get { return fMenuEstado; }
            set { SetPropertyValue<bool>(nameof(MenuEstado), ref fMenuEstado, value); }
        }
        bool fMenuReporte;
        public bool MenuReporte
        {
            get { return fMenuReporte; }
            set { SetPropertyValue<bool>(nameof(MenuReporte), ref fMenuReporte, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"EmpleadoReferencesRol")]
        public XPCollection<Empleado> Empleadoes { get { return GetCollection<Empleado>(nameof(Empleadoes)); } }
    }

}
