//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData ExecspAgregarRol(Session session, string NombreRol, bool MenuRol, bool MenuEmpleado, bool MenuMantenimiento, bool MenuAlmacen, bool MenuCompra, bool MenuVenta, bool MenuReporte, DateTime FechaRegistro)
        {
            return session.ExecuteSproc("spAgregarRol", new OperandValue(NombreRol), new OperandValue(MenuRol), new OperandValue(MenuEmpleado), new OperandValue(MenuMantenimiento), new OperandValue(MenuAlmacen), new OperandValue(MenuCompra), new OperandValue(MenuVenta), new OperandValue(MenuReporte), new OperandValue(FechaRegistro));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspAgregarTema(Session session, string NombreTema)
        {
            return session.ExecuteSproc("spAgregarTema", new OperandValue(NombreTema));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspEjecutarAgregar(Session session, string spAgregarTema)
        {
            return session.ExecuteSproc("spEjecutarAgregar", new OperandValue(spAgregarTema));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspExecInsertarCambioDolar(Session session, string spInsertarCambioDolar)
        {
            return session.ExecuteSproc("spExecInsertarCambioDolar", new OperandValue(spInsertarCambioDolar));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspInsertarCambioDolar(Session session, decimal ValorDolar, DateTime FechaRegistro)
        {
            return session.ExecuteSproc("spInsertarCambioDolar", new OperandValue(ValorDolar), new OperandValue(FechaRegistro));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspModificarTema(Session session, int Id, int IdTema)
        {
            return session.ExecuteSproc("spModificarTema", new OperandValue(Id), new OperandValue(IdTema));
        }
    }
}
