//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData Execsp_alterdiagram(Session session, string diagramname, int owner_id, int version, byte[] definition)
        {
            return session.ExecuteSproc("sp_alterdiagram", new OperandValue(diagramname), new OperandValue(owner_id), new OperandValue(version), new OperandValue(definition));
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_creatediagram(Session session, string diagramname, int owner_id, int version, byte[] definition)
        {
            return session.ExecuteSproc("sp_creatediagram", new OperandValue(diagramname), new OperandValue(owner_id), new OperandValue(version), new OperandValue(definition));
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_dropdiagram(Session session, string diagramname, int owner_id)
        {
            return session.ExecuteSproc("sp_dropdiagram", new OperandValue(diagramname), new OperandValue(owner_id));
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_helpdiagramdefinition(Session session, string diagramname, int owner_id)
        {
            return session.ExecuteSproc("sp_helpdiagramdefinition", new OperandValue(diagramname), new OperandValue(owner_id));
        }
        public static System.Collections.Generic.ICollection<sp_helpdiagramdefinitionResult> Execsp_helpdiagramdefinitionIntoObjects(Session session, string diagramname, int owner_id)
        {
            return session.GetObjectsFromSproc<sp_helpdiagramdefinitionResult>("sp_helpdiagramdefinition", new OperandValue(diagramname), new OperandValue(owner_id));
        }
        public static XPDataView Execsp_helpdiagramdefinitionIntoDataView(Session session, string diagramname, int owner_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_helpdiagramdefinition", new OperandValue(diagramname), new OperandValue(owner_id));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(sp_helpdiagramdefinitionResult)), sprocData);
        }
        public static void Execsp_helpdiagramdefinitionIntoDataView(XPDataView dataView, Session session, string diagramname, int owner_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_helpdiagramdefinition", new OperandValue(diagramname), new OperandValue(owner_id));
            dataView.PopulateProperties(session.GetClassInfo(typeof(sp_helpdiagramdefinitionResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_helpdiagrams(Session session, string diagramname, int owner_id)
        {
            return session.ExecuteSproc("sp_helpdiagrams", new OperandValue(diagramname), new OperandValue(owner_id));
        }
        public static System.Collections.Generic.ICollection<sp_helpdiagramsResult> Execsp_helpdiagramsIntoObjects(Session session, string diagramname, int owner_id)
        {
            return session.GetObjectsFromSproc<sp_helpdiagramsResult>("sp_helpdiagrams", new OperandValue(diagramname), new OperandValue(owner_id));
        }
        public static XPDataView Execsp_helpdiagramsIntoDataView(Session session, string diagramname, int owner_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_helpdiagrams", new OperandValue(diagramname), new OperandValue(owner_id));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(sp_helpdiagramsResult)), sprocData);
        }
        public static void Execsp_helpdiagramsIntoDataView(XPDataView dataView, Session session, string diagramname, int owner_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_helpdiagrams", new OperandValue(diagramname), new OperandValue(owner_id));
            dataView.PopulateProperties(session.GetClassInfo(typeof(sp_helpdiagramsResult)));
            dataView.LoadData(sprocData);
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_renamediagram(Session session, string diagramname, int owner_id, string new_diagramname)
        {
            return session.ExecuteSproc("sp_renamediagram", new OperandValue(diagramname), new OperandValue(owner_id), new OperandValue(new_diagramname));
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_upgraddiagrams(Session session)
        {
            return session.ExecuteSproc("sp_upgraddiagrams");
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspAgregarRol(Session session, string NombreRol, bool MenuRol, bool MenuEmpleado, bool MenuMantenimiento, bool MenuAlmacen, bool MenuCompra, bool MenuVenta, bool MenuReporte, DateTime FechaRegistro)
        {
            return session.ExecuteSproc("spAgregarRol", new OperandValue(NombreRol), new OperandValue(MenuRol), new OperandValue(MenuEmpleado), new OperandValue(MenuMantenimiento), new OperandValue(MenuAlmacen), new OperandValue(MenuCompra), new OperandValue(MenuVenta), new OperandValue(MenuReporte), new OperandValue(FechaRegistro));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspAgregarTema(Session session, string NombreTema)
        {
            return session.ExecuteSproc("spAgregarTema", new OperandValue(NombreTema));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspEjecutarAgregar(Session session, string spAgregarTema)
        {
            return session.ExecuteSproc("spEjecutarAgregar", new OperandValue(spAgregarTema));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspExecInsertarCambioDolar(Session session, string spInsertarCambioDolar)
        {
            return session.ExecuteSproc("spExecInsertarCambioDolar", new OperandValue(spInsertarCambioDolar));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspInsertarCambioDolar(Session session, decimal ValorDolar, DateTime FechaRegistro)
        {
            return session.ExecuteSproc("spInsertarCambioDolar", new OperandValue(ValorDolar), new OperandValue(FechaRegistro));
        }
        public static DevExpress.Xpo.DB.SelectedData ExecspModificarTema(Session session, int Id, int IdTema)
        {
            return session.ExecuteSproc("spModificarTema", new OperandValue(Id), new OperandValue(IdTema));
        }
    }
}
