//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Tema : XPLiteObject
    {
        int fIdTema;
        [Key(true)]
        public int IdTema
        {
            get { return fIdTema; }
            set { SetPropertyValue<int>(nameof(IdTema), ref fIdTema, value); }
        }
        string fNombreTema;
        [Size(60)]
        public string NombreTema
        {
            get { return fNombreTema; }
            set { SetPropertyValue<string>(nameof(NombreTema), ref fNombreTema, value); }
        }
        [Association(@"EmpleadoReferencesTema")]
        public XPCollection<Empleado> Empleadoes { get { return GetCollection<Empleado>(nameof(Empleadoes)); } }
    }

}
