//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Sistemaventa.Sistema_Venta
{

    public partial class Venta : XPLiteObject
    {
        int fIdVenta;
        [Key(true)]
        public int IdVenta
        {
            get { return fIdVenta; }
            set { SetPropertyValue<int>(nameof(IdVenta), ref fIdVenta, value); }
        }
        Cliente fIdClient;
        [Association(@"VentaReferencesCliente")]
        public Cliente IdClient
        {
            get { return fIdClient; }
            set { SetPropertyValue<Cliente>(nameof(IdClient), ref fIdClient, value); }
        }
        Empleado fIdEmpleado;
        [Association(@"VentaReferencesEmpleado")]
        public Empleado IdEmpleado
        {
            get { return fIdEmpleado; }
            set { SetPropertyValue<Empleado>(nameof(IdEmpleado), ref fIdEmpleado, value); }
        }
        string fTipoDocumento;
        [Size(20)]
        public string TipoDocumento
        {
            get { return fTipoDocumento; }
            set { SetPropertyValue<string>(nameof(TipoDocumento), ref fTipoDocumento, value); }
        }
        string fDocumentoVenta;
        [Size(12)]
        public string DocumentoVenta
        {
            get { return fDocumentoVenta; }
            set { SetPropertyValue<string>(nameof(DocumentoVenta), ref fDocumentoVenta, value); }
        }
        decimal fMontoPago;
        public decimal MontoPago
        {
            get { return fMontoPago; }
            set { SetPropertyValue<decimal>(nameof(MontoPago), ref fMontoPago, value); }
        }
        decimal fMontoCambio;
        public decimal MontoCambio
        {
            get { return fMontoCambio; }
            set { SetPropertyValue<decimal>(nameof(MontoCambio), ref fMontoCambio, value); }
        }
        string fTipoPago;
        [Size(8)]
        public string TipoPago
        {
            get { return fTipoPago; }
            set { SetPropertyValue<string>(nameof(TipoPago), ref fTipoPago, value); }
        }
        CambioDolar fIdCambio;
        [Association(@"VentaReferencesCambioDolar")]
        public CambioDolar IdCambio
        {
            get { return fIdCambio; }
            set { SetPropertyValue<CambioDolar>(nameof(IdCambio), ref fIdCambio, value); }
        }
        int fDescuento;
        [ColumnDbDefaultValue("((0))")]
        public int Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<int>(nameof(Descuento), ref fDescuento, value); }
        }
        decimal fMontoTotal;
        public decimal MontoTotal
        {
            get { return fMontoTotal; }
            set { SetPropertyValue<decimal>(nameof(MontoTotal), ref fMontoTotal, value); }
        }
        DateTime fFechaRegistro;
        [ColumnDbDefaultValue("(getdate())")]
        public DateTime FechaRegistro
        {
            get { return fFechaRegistro; }
            set { SetPropertyValue<DateTime>(nameof(FechaRegistro), ref fFechaRegistro, value); }
        }
        [Association(@"DetalleVentaReferencesVenta")]
        public XPCollection<DetalleVenta> DetalleVentas { get { return GetCollection<DetalleVenta>(nameof(DetalleVentas)); } }
        [Association(@"EstadoVentaReferencesVenta")]
        public XPCollection<EstadoVenta> EstadoVentas { get { return GetCollection<EstadoVenta>(nameof(EstadoVentas)); } }
    }

}
